version: '3.7'
services:
  vereinapi2:
    image: vereinapi2
    build: .
    ports:
      - 80:80
      - 443:443
    environment:
       - DBSettings__Host=yourhost
       - DBSettings__UserID=userid
       - DBSettings__Password=dbpass
       - DBSettings__Database=dbname
       - DBSettings__Port=3306
       - JWT__Secret=yoursecret
       - 'ConnectionStrings__IdentityDB=Data Source=./IDFiles/Identity.db'
       - EmailSettings__Host=yourhost
       - EmailSettings__Port=yourport

volumes:
   wwwroot: {}